### ISSUE TITLE
빌드 시 @babel/core 모듈이 필요함.

### ISSUE THREAD

**Issue by chkim116** [CafeReview/Front_End#3]
- yarn build 시 @babel/core가 없어 에러가 남.

![빌드에러](https://images.velog.io/images/chkim132/post/7b369ad7-2996-42ae-8224-5d0230da71de/%EB%B9%8C%EB%93%9C%EC%8B%9C%EC%97%90%EB%9F%AC.png)

**Comment by holim0** [comment]
@babel/core를 설치하면 문제가 해결되나요?

**Comment by chkim116** [comment]
> @babel/core를 설치하면 문제가 해결되나요?

넵 정상적으로 build 처리가 됩니다
